### ISSUE TITLE
[NEW]: Add suckless tools and wrappers

### ISSUE THREAD

**Issue by yuri-norwood** [yuri-norwood/dotfiles#203]
**Configuration for:**
All suckless tools, particularly, `dwm(1)`, `surf(1)`, `st(1)`, and `dmenu(1)`.

**Files required:**
* [x] #242 [NEW]: Add .dwm config and source
* [x] #243 [NEW]: Add .surf config and source
* [x] #244 [NEW]: Add .st config and source
* [x] #245 [NEW]: Add .dmenu config and source
* [x] #241 [NEW]: Add .bin/suckless to hold wrappers and helpers
* [ ] #254 [NEW]: Add patching makefile to suckless configs

**Comment by yuri-norwood** [comment]
Closing as only #254 remains incomplete.
